### ISSUE TITLE
Magento Versioning. Create a Util class for defining a Magento version

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/magento2-phpstorm-plugin#51]
Some of the plugin functionality might be dependent on the Magento version. We need to introduce a util class for Magento version resolving.

Acceptance criteria:
* Util is created
* Magento version is shown in the settings (etc):
![image](https://user-images.githubusercontent.com/20116393/77422639-7e713a00-6dd6-11ea-981b-59829ef2c912.png)

**Comment by vasilii-b** [comment]
Hi @VitaliyBoyko,
May I grab this one?
Thanks!

**Comment by VitaliyBoyko** [comment]
Sure 🙇

**Comment by VitaliyBoyko** [comment]
Version should be grabbed from the composer.json. Probably we need to introduce new hard dependency (grade.build, plugin.xml) https://plugins.jetbrains.com/plugin/7631-php-composer-json-support. Please investigate this point. Thank you!

**Comment by vasilii-b** [comment]
Hi @VitaliyBoyko,
It seems I've found the place where the Magento grabs the current version to show in the admin area footer.

https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/App/ProductMetadata.php#L78-L92

It all starts with
https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/app/code/Magento/Backend/view/adminhtml/templates/page/footer.phtml#L9

Then goes to
https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/app/code/Magento/Backend/Block/Page/Footer.php#L56-L59

So, in the end the Magento codebase is dependent on the `composer.json` file too in order to get the current version.

Thank you!

**Comment by vasilii-b** [comment]
Also, maybe it is worth it to have the Magento version type as well in scope of this issue?
I mean showing whenever the version is CE or EE.
What do you say, @VitaliyBoyko ?

**Comment by VitaliyBoyko** [comment]
Ok, then, let's use the `composer.json`. 

I don't really see the reason for defining an edition of a Magento so far. Could you please provide the use-case?
However, 
 let's concentrate on the version in the scope of this task. I would create a separate one for the edition.

Thank you!
